"""Initial migration

Revision ID: 77d1e5fa1445
Revises: 7c23a183598b
Create Date: 2024-03-13 15:10:47.716618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d1e5fa1445'
down_revision = '7c23a183598b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('admin_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_added', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('added_by_admin')

    op.drop_table('user')
    # ### end Alembic commands ###
